package entity;

import lombok.Data;

import java.util.Date;
@Data
public class MemberAtMsg extends BaseEntity {

    private String tips;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.uuid
     *
     * @mbg.generated
     */
    private Integer uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.receive_member_uuid
     *
     * @mbg.generated
     */
    private String receiveMemberUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.send_member_uuid
     *
     * @mbg.generated
     */
    private String sendMemberUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.data_type
     *
     * @mbg.generated
     */
    private Integer dataType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.post_uuid
     *
     * @mbg.generated
     */
    private String postUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.comment_uuid
     *
     * @mbg.generated
     */
    private String commentUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.is_read
     *
     * @mbg.generated
     */
    private Integer isRead = 0;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_member_at_msg.last_modify_time
     *
     * @mbg.generated
     */
    private Date lastModifyTime;
}